perusahaan_login/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'callback/$', callback, name='callback'),
]

perusahaan_lowongan/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add-forum/$', add_forum, name='add-forum'),
    url(r'^add-comment/(?P<id>.*)/$', add_comment, name='add-comment'),
]

perusahaan_profile/urls.py
from django.conf.urls import url
from .views import *
#url for app
urlpatterns = [
    url(r'^$', show_profile, name='showProfile'),
]

sambungin2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import perusahaan_login.urls as perusahaan_login
import perusahaan_lowongan.urls as perusahaan_lowongan
import perusahaan_profile.urls as perusahaan_profile

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^perusahaan_login/', include(perusahaan_login,namespace='perusahaan_login')),
    url(r'^$', RedirectView.as_view(url='perusahaan_login/', permanent = True), name = '$'),
    url(r'^perusahaan-lowongan/', include(perusahaan_lowongan, namespace='perusahaan-lowongan')),
    url(r'^perusahaan_profile/', include(perusahaan_profile, namespace='perusahaan_profile')),
]

perusahaan_login/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Pengguna(models.Model):
    kode_identitas = models.CharField('Kode Identitas', max_length=20, primary_key=True, )
    nama = models.CharField('Nama', max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

perusahaan_lowongan/models.py
from django.db import models

# Create your models here.
# class Perusahaan(models.Model):
#     logo_url = models.URLField(default="https://maxcdn.icons8.com/Share/icon/Users//user_male_circle_filled1600.png")
#     name = models.CharField(max_length=30)
#     tipe_perusahaan = models.CharField(max_length=30)
#     website_url = models.CharField(max_length=100)

class Forum(models.Model):
    # perusahaan = models.ForeignKey(Perusahaan)
    website_url = models.CharField(max_length=100)
    lowongan = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

class Comment(models.Model):
	# perusahaan = models.ForeignKey(Perusahaan)
	forum = models.ForeignKey(Forum)
	comment = models.TextField()
	created_date = models.DateTimeField(auto_now_add=True)

perusahaan_profile/models.py
from django.db import models

# Create your models here.

perusahaan_utama/models.py
from django.db import models

# Create your models here.

perusahaan_lowongan/forms.py
from django import forms

class Forum_Form(forms.Form):
    error_messages = {
        'required': 'is empty',
    }
    description_attrs = {
    'type': 'text',
    'cols': 50,
    'rows': 4,
    'class': 'forum-form-textarea',
    'placeholder':'Masukan deskripsi lowongan kerja'
    }
    description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

class Comment_Form(forms.Form):
    error_messages = {
        'required': 'is empty',
    }
    description_attrs = {
    'type': 'text',
    'cols': 50,
    'rows': 2,
    'class': 'forum-form-textarea',
    'placeholder':'Masukan comment...'
    }
    description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

perusahaan_login/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
import requests
# Create your views here.

res = {}
def index(request):
    res['author'] = "Nurhikmah Ilmi"
    html = 'login/login.html'
    return render(request, html, res)

def callback(request):
    print("masuk sini")
    if request.method == "GET":
        code = request.GET.get('code', '')

        url = "https://www.linkedin.com/oauth/v2/accessToken"

        params = {
            "grant_type" : "authorization_code",
            "code" : str(code),
            "redirect_uri" : "http://localhost:8000/perusahaan_login/callback",
            "client_id" : "81zelqgz00u6jy",
            "client_secret" : "o7G9nxtmLw6rQ6FL"
        }

        accessToken = requests.get(url, params=params).json()['access_token']

        params = {
            "oauth2_access_token" : accessToken,
            "format" : "json",
            "is-company-admin" : "true"
        }
        url2 = "https://api.linkedin.com/v1/companies"

        companyId = requests.get(url2, params=params).json()['values'][0]['id']

        params = {
            "oauth2_access_token" : accessToken,
            "format" : "json"
        }
        url3 = "https://api.linkedin.com/v1/companies/"+str(companyId)+":(name,company-type,website-url,logo-url,specialties)"
        print("url13nya yang ini")
        print(url3)
        jr = requests.get(url3, params=params).json()
        print(jr)
        print("Halo")
        tipePerusahaan = jr['companyType']['name']
        logoUrl = jr["logoUrl"]
        name = jr["name"]
        specialties = jr["specialties"]["values"]
        print(type(specialties))
        websiteUrl = jr["websiteUrl"]

        response = {}

        response["name"] = name
        response["logoUrl"] = logoUrl
        response["tipePerusahaan"] = tipePerusahaan
        response["specialties"] = specialties
        response["websiteUrl"] = websiteUrl

        request.session['name'] = name
        request.session['logoUrl'] = logoUrl
        request.session['tipePerusahaan'] = tipePerusahaan
        request.session['websiteUrl'] = websiteUrl

        return render(request, "perusahaan_profile/layout/base.html", response)


    return HttpResponseRedirect(reverse('perusahaan_login:index'))

perusahaan_lowongan/views.py
from django.shortcuts import render
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect, HttpResponse
from .forms import Forum_Form, Comment_Form
from .models import Forum, Comment
# from perusahaan_profile.models import Perusahaan


response={}
# Create your views here.
def index(request):
    if 'name' not in request.session:
        return HttpResponseRedirect(reverse('perusahaan_login:index'))
    else:    # pragma: no cover
        perusahaan = request.session['websiteUrl']

        forum = Forum.objects.filter(website_url=perusahaan).order_by('-created_date')
        # forum = Forum.objects.all().order_by('-created_date')
        # forum_haha = Forum.objects.get(lowongan="DFSAF")

        paginator = Paginator(forum, 1)
        page = request.GET.get('page', 1)
        try:
            halaman = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            halaman = paginator.page(1)
        except EmptyPage:
            halaman = paginator.page(paginator.num_pages)

        response['nama_perusahaan'] = request.session['name']
        response['logo_url'] = request.session['logoUrl']
        response['forum_list'] = halaman
        html = 'perusahaan_lowongan/forum.html'
        response['forum_form'] = Forum_Form
        return render(request, html, response)



def add_forum(request): # pragma: no cover
    form = Forum_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['lowongan'] = request.POST['description']
        web_url = request.session['websiteUrl']
        forum = Forum(lowongan=response['lowongan'], website_url=web_url)
        forum.save()
        return HttpResponseRedirect('/perusahaan-lowongan/')
    else:
        return HttpResponseRedirect('/perusahaan-lowongan/')

def add_comment(request, id):   # pragma: no cover
    forum = Forum.objects.get(id=id)
    form = Comment_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['comment'] = request.POST['description']
        comment = Comment(comment=response['comment'], forum=forum)
        comment.save()
        return HttpResponseRedirect('/perusahaan-lowongan/')
    else:
        return HttpResponseRedirect('/perusahaan-lowongan/')

perusahaan_profile/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response

# Create your views here.

response = {}

def show_profile(request):
    return render_to_response('perusahaan_profile/layout/base.html')

perusahaan_utama/views.py
from django.shortcuts import render

# Create your views here.

perusahaan_login/templates/login.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">

   <meta name="author" content="{{author}}">
   <!-- bootstrap csss -->
   <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">
   <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">

   <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700">

   <title>
       {% block title %} Welcome to PT. !Suka PPW {% endblock %}
   </title>

</head>
<body>

    <content>


	<p id="baton"></p>
	<div id="profileData" style="display: none;">
		<p id="name"></p>
	</div>
	<!-- sign in with linkedin button -->
	<script type="in/Login"></script>

	<section>
	    <h1 class="forum-list-title"> Forum Lowongan Kerja</h1>
	    <div class="container">
	            {% if forum_list %}
	                {% for forum in forum_list %}
	                <div class="card">
	                  <img src={{ logo_url }}>
	                    <h1> {{ nama_perusahaan }} </h1>
	                    <h4> {{ forum.lowongan }}</h4>
	                    <button style="float: right;" id="response" class="btn" onclick=showCommand()> Response
	                    </button>
	                    <p> {{ forum.created_date}}</p>
	                </div>
	                <div id="comment-container" style="display:none" class="container">
	                  <form id="comment" method="POST" action="{% url 'perusahaan-lowongan:add-comment' forum.id %}">
	                      <h2 id="comment-title">Tambah Comment</h2>
	                      {% csrf_token %}
	                      {{ forum_form }}
	                      <input id="submit" type="submit" class="btn btn-lg btn-block btn-info submit" value="Submit">
	                      <br>
	                  </form>
	                </div>
	                <div class="comment-container">
	                    {% if forum.comment_set.all %}
	                        {% for comment in forum.comment_set.all %}

	                            <h4> {{comment.comment}} </h4>
	                            <h6> {{comment.created_date}} </h6>

	                        {% endfor %}
	                    {% endif %}
	                      </div>


	                {% endfor %}
	            {% else %}
	            <div class="alert alert-danger text-center">
	                <strong>Maaf!</strong> Tidak ada forum
	            </div>
	            {% endif %}
	        </div>

	        <div class="pagination">
	                <span class="step-links">
	                    {% if forum_list.has_previous %}
	                        <a href="?page={{ forum_list.previous_page_number }}">previous</a>
	                    {% endif %}

	                    <span class="current">
	                        Page {{ forum_list.number }} of {{ forum_list.paginator.num_pages }}.
	                    </span>

	                    {% if forum_list.has_next %}
	                        <a href="?page={{ forum_list.next_page_number }}">next</a>
	                    {% endif %}
	                </span>
	            </div>
	</section>
	<button id="new_forum" class="btn btn-lg" onclick="show()"> Tambah Forum Lowongan </button>

	<div id="form" style="display:none" class="container">
	  <form id="insert_forum"  method="POST" action="{% url 'perusahaan-lowongan:add-forum' %}">
	      <h2 id="forum-title">Tambah Forum Lowongan Kerja</h2>
	      {% csrf_token %}
	      {{ forum_form }}
	      <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
	      <br>
	  </form>
	</div>


	<script>
	function show(){
	    var x = document.getElementById("form");
	    if(x.style.display === "none"){
	      x.style.display = "block";
	    }else{
	      x.style.display = "none";
	    }
	    $('#new_forum').hide();
	}

	// function add(){
	//   var x = document.getElementById("form");
	//   if(x.style.display === "none"){
	//     x.style.display = "block";
	//   }else{
	//     x.style.display = "none";
	//   }
	//   $('#new_forum').show();
	// }

	function showCommand(){
	  var x = document.getElementById("comment-container");
	  if(x.style.display === "none"){
	    x.style.display = "block";
	  }else{
	    x.style.display = "none";
	  }
	  $('#response').hide();
	}
	//
	// function addCommand(){
	//   var x = document.getElementById("comment-container");
	//   if(x.style.display === "none"){
	//     x.style.display = "block";
	//   }else{
	//     x.style.display = "none";
	//   }
	//   $('#response').show();
	// }
	</script>

</content>
    <footer>
       <!-- TODO Block Footer dan include footer.html -->
       {% block footer %}
       {% include "partials/footer.html" %}
       {% endblock %}
    </footer>
	<script type="text/javascript" src="//platform.linkedin.com/in.js">
		api_key:   81zelqgz00u6jy
		onLoad:    onLinkedInLoad
		authorize: true
	</script>

</body>
</html>

perusahaan_login/templates/login/company.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="login">
    <meta name="author" content="R">
    <title>{{ name }}</title>
</head>

<body>
    <img src="{{ logoUrl }}" alt="">
    <p>{{ name }}</p>
    <p>{{ tipePerusahaan }}</p>
    <ul>
    {% for i in specialties %}
        <li>{{ i }}</li>
    {% endfor %}
    </ul>
    <p>{{ websiteUrl }}</p>
    <a href="{% url 'perusahaan-lowongan:index'%}"> direct to forum lowongan kerja </a>
</body>
</html>

perusahaan_login/templates/login/login.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="login">
    <meta name="author" content="R">
    <title>PT. !suka PPW Log in</title>
<style>
.button {
    background-color: #4CAF50; /* Green */
    border: none;
    color: white;
    padding: 16px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    -webkit-transition-duration: 0.4s; /* Safari */
    transition-duration: 0.4s;
    cursor: pointer;
}
.button2 {
    background-color: white; 
    color: black; 
    border: 2px solid #008CBA;
}
.button2:hover {
    background-color: #008CBA;
    color: white;
}
/* animasi pada title */
.main-title{
  -webkit-animation: colorchange 1s infinite;
  -webkit-animation-direction: alternate;
  text-align: center;
}

/* animasi colorchange */
@-webkit-keyframes colorchange {
    0% {
        -webkit-text-stroke: 5px #0fb8ad;
    letter-spacing: 0;
    }
  50% {
    -webkit-text-stroke: 7.5px  #1fc8db;
  }
    100% {
        -webkit-text-stroke: 10px  #2cb5e8;
    letter-spacing: 18px;
    }
}
#input-list form > h2{
  font-size: 1.3em;
  text-transform: uppercase;
  color: #2C3E50;
  margin-bottom: 10px;
}

</style>
</head>

<body>
	<h1 class="main-title">!Suka PPW</h1> <!-- ini css -->
	<section name="input-list" id="input-list">  
		<div class="container">
			<h2>Perusahaan !suka PPW membuka peluang untuk:</h2>
				<p>1. Web Develper</p>
				<p>2. Mobile Develper</p>
				
		</div>
	</section>	
	<section name="button-button" id="button-button">
		<div class="container"> <!-- ini css -->
			<a href="https://www.linkedin.com/oauth/v2/authorization?response_type=code&client_id=81zelqgz00u6jy&redirect_uri=http://localhost:8000/perusahaan_login/callback&state=987654321" class="button" class="button button2">Log in with LinkedIn</a>
		</div>
	</section>

    <a href="https://www.linkedin.com/oauth/v2/authorization?response_type=code&client_id=81zelqgz00u6jy&redirect_uri=http://localhost:8000/perusahaan_login/callback&state=987654321">lelah:(</a>


    <section>
  	    <h1 class="forum-list-title"> Forum Lowongan Kerja</h1>
  	    <div class="container">
  	            {% if forum_list %}
  	                {% for forum in forum_list %}
  	                <div class="card">
  	                  <img src={{ logo_url }}>
  	                    <h1> {{ nama_perusahaan }} </h1>
  	                    <h4> {{ forum.lowongan }}</h4>
  	                    <button style="float: right;" id="response" class="btn" onclick=showCommand()> Response
  	                    </button>
  	                    <p> {{ forum.created_date}}</p>
  	                </div>
  	                <div id="comment-container" style="display:none" class="container">
  	                  <form id="comment" method="POST" action="{% url 'perusahaan-lowongan:add-comment' forum.id %}">
  	                      <h2 id="comment-title">Tambah Comment</h2>
  	                      {% csrf_token %}
  	                      {{ forum_form }}
  	                      <input id="submit" type="submit" class="btn btn-lg btn-block btn-info submit" value="Submit">
  	                      <br>
  	                  </form>
  	                </div>
  	                <div class="comment-container">
  	                    {% if forum.comment_set.all %}
  	                        {% for comment in forum.comment_set.all %}

  	                            <h4> {{comment.comment}} </h4>
  	                            <h6> {{comment.created_date}} </h6>

  	                        {% endfor %}
  	                    {% endif %}
  	                      </div>


  	                {% endfor %}
  	            {% else %}
  	            <div class="alert alert-danger text-center">
  	                <strong>Maaf!</strong> Tidak ada forum
  	            </div>
  	            {% endif %}
  	        </div>

  	        <div class="pagination">
  	                <span class="step-links">
  	                    {% if forum_list.has_previous %}
  	                        <a href="?page={{ forum_list.previous_page_number }}">previous</a>
  	                    {% endif %}

  	                    <span class="current">
  	                        Page {{ forum_list.number }} of {{ forum_list.paginator.num_pages }}.
  	                    </span>

  	                    {% if forum_list.has_next %}
  	                        <a href="?page={{ forum_list.next_page_number }}">next</a>
  	                    {% endif %}
  	                </span>
  	            </div>
  	</section>
  	<button id="new_forum" class="btn btn-lg" onclick="show()"> Tambah Forum Lowongan </button>

  	<div id="form" style="display:none" class="container">
  	  <form id="insert_forum"  method="POST" action="{% url 'perusahaan-lowongan:add-forum' %}">
  	      <h2 id="forum-title">Tambah Forum Lowongan Kerja</h2>
  	      {% csrf_token %}
  	      {{ forum_form }}
  	      <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
  	      <br>
  	  </form>
  	</div>


  	<script>
  	function show(){
  	    var x = document.getElementById("form");
  	    if(x.style.display === "none"){
  	      x.style.display = "block";
  	    }else{
  	      x.style.display = "none";
  	    }
  	    $('#new_forum').hide();
  	}

  	// function add(){
  	//   var x = document.getElementById("form");
  	//   if(x.style.display === "none"){
  	//     x.style.display = "block";
  	//   }else{
  	//     x.style.display = "none";
  	//   }
  	//   $('#new_forum').show();
  	// }

  	function showCommand(){
  	  var x = document.getElementById("comment-container");
  	  if(x.style.display === "none"){
  	    x.style.display = "block";
  	  }else{
  	    x.style.display = "none";
  	  }
  	  $('#response').hide();
  	}
  	//
  	// function addCommand(){
  	//   var x = document.getElementById("comment-container");
  	//   if(x.style.display === "none"){
  	//     x.style.display = "block";
  	//   }else{
  	//     x.style.display = "none";
  	//   }
  	//   $('#response').show();
  	// }
  	</script>

</body>
</html>

perusahaan_lowongan/templates/perusahaan_lowongan/forum.html
{% extends "perusahaan_lowongan/layout/base.html" %}
{% load staticfiles %}
{% load static %}
{% block content%}

<section>
    <h1 class="forum-list-title"> Forum Lowongan Kerja</h1>
    <div class="container">
            {% if forum_list %}
                {% for forum in forum_list %}
                <div class="card">
                  <img src={{ logo_url }}>
                    <h1> {{ nama_perusahaan }} </h1>
                    <h4> {{ forum.lowongan }}</h4>
                    <button style="float: right;" id="response" class="btn" onclick=showCommand()> Response
                    </button>
                    <p> {{ forum.created_date}}</p>
                </div>
                <div id="comment-container" style="display:none" class="container">
                  <form id="comment" method="POST" action="{% url 'perusahaan-lowongan:add-comment' forum.id %}">
                      <h2 id="comment-title">Tambah Comment</h2>
                      {% csrf_token %}
                      {{ forum_form }}
                      <input id="submit" type="submit" class="btn btn-lg btn-block btn-info submit" value="Submit">
                      <br>
                  </form>
                </div>
                <div class="comment-container">
                    {% if forum.comment_set.all %}
                        {% for comment in forum.comment_set.all %}

                            <h4> {{comment.comment}} </h4>
                            <h6> {{comment.created_date}} </h6>

                        {% endfor %}
                    {% endif %}
                      </div>


                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Maaf!</strong> Tidak ada forum
            </div>
            {% endif %}
        </div>

        <div class="pagination">
                <span class="step-links">
                    {% if forum_list.has_previous %}
                        <a href="?page={{ forum_list.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ forum_list.number }} of {{ forum_list.paginator.num_pages }}.
                    </span>

                    {% if forum_list.has_next %}
                        <a href="?page={{ forum_list.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
</section>
<button id="new_forum" class="btn btn-lg" onclick="show()"> Tambah Forum Lowongan </button>

<div id="form" style="display:none" class="container">
  <form id="insert_forum"  method="POST" action="{% url 'perusahaan-lowongan:add-forum' %}">
      <h2 id="forum-title">Tambah Forum Lowongan Kerja</h2>
      {% csrf_token %}
      {{ forum_form }}
      <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
      <br>
  </form>
</div>


{% block javascript%}
<script>
function show(){
    var x = document.getElementById("form");
    if(x.style.display === "none"){
      x.style.display = "block";
    }else{
      x.style.display = "none";
    }
    $('#new_forum').hide();
}

// function add(){
//   var x = document.getElementById("form");
//   if(x.style.display === "none"){
//     x.style.display = "block";
//   }else{
//     x.style.display = "none";
//   }
//   $('#new_forum').show();
// }

function showCommand(){
  var x = document.getElementById("comment-container");
  if(x.style.display === "none"){
    x.style.display = "block";
  }else{
    x.style.display = "none";
  }
  $('#response').hide();
}
//
// function addCommand(){
//   var x = document.getElementById("comment-container");
//   if(x.style.display === "none"){
//     x.style.display = "block";
//   }else{
//     x.style.display = "none";
//   }
//   $('#response').show();
// }
</script>
{% endblock %}
{% endblock %}

perusahaan_lowongan/templates/perusahaan_lowongan/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="description" content="perusahaan lowongan">
   <meta name="author" content="{{author}}">
   <!-- bootstrap csss -->
   <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css?family=Oxygen" rel="stylesheet">
   <link rel="stylesheet" type="text/css" href="{% static 'css/lowongan.css' %}" />
   <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700">

   <title>
       {% block title %} Forum Lowongan Kerja {% endblock %}
   </title>
</head>
<body>
   <header>
      {% include "perusahaan_lowongan/partials/header.html" %}
   </header>
   <content>
           {% block content %}
               <!-- content goes here -->
           {% endblock %}
   </content>
   <footer>
       <!-- TODO Block Footer dan include footer.html -->
       {% block footer %}

       {% endblock %}
   </footer>
   <!-- Jquery n Bootstrap Script -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
   <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   {% block javascript %}
   {% endblock %}
</body>
</html>

perusahaan_lowongan/templates/perusahaan_lowongan/partials/header.html
  <!-- Fixed navbar -->
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container" id="header-bg">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a id="home-title" class="navbar-brand" href="{% url 'perusahaan_login:index' %}">Home</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <!-- LINK MENUJU table, dan link menuju home#form -->
          <li><a id="nav-profile" href="#}"> Profile </a></li>
          <li><a id="nav-forum" href="{% url 'perusahaan-lowongan:index' %}"> Discussion </a> </li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>